services:
  redis:
    image: redis:7-alpine
    container_name: reservas-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - reservas-network

volumes:
  redis_data:
    name: reservas_redis_data

networks:
  reservas-network:
    name: reservas-network
    driver: bridge