spring.config.import=optional:file:.env[.properties]

spring.application.name=Reservas_api


# Base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# Manejo de errores (no exponer detalles internos)
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

# Flyway
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true


# Servidor
server.port=${SERVER_PORT:8080}

# CORS
#app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-minutes=${JWT_ACCESS_EXPIRATION_MINUTES:30}
app.jwt.refresh-expiration-days=${JWT_REFRESH_EXPIRATION_DAYS:7}
